"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['gierzwaluw/gui.py']
DATA_FILES = [('static', ['static/swallow.png', 'static/index.html'])]
OPTIONS = {
    'argv_emulation': True,
    'iconfile':'static/swallow.icns',
    'plist': {
        "LSUIElement": True,
    },
}

setup(
    name="Gierzwaluw",
    packages=['gierzwaluw'],
    scripts=['gierzwaluw/gui.py', 'gierzwaluw/cli.py'],
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
